<?php
 //definim aici arrays cu date
$users = array("student" => "test", "marius" => "1234");
$links = array("InfoAcademy" => "http://www.infoacademy.net", "PHP Romania" => "http://phpromania.net/", "PHP.net"=>"http://php.net");
$home = "index.php";

$ipsum = <<<ipsum
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ipsum diam, tempus vitae venenatis non, vulputate non quam. Morbi ultricies egestas risus vel lobortis. Pellentesque malesuada eros sit amet risus sagittis non venenatis nibh lacinia. Ut at leo felis, id rutrum risus. Morbi libero ligula, auctor eget elementum at, suscipit sed quam. Donec augue erat, convallis ac vulputate vel, aliquam eget felis. Maecenas tellus diam, condimentum sit amet accumsan non, iaculis et risus. Nullam felis nisi, tempor ac molestie quis, pretium et nulla. Fusce nec augue in metus blandit faucibus sit amet bibendum est. Nulla facilisi. Suspendisse potenti. Sed congue egestas mi, id consectetur quam fermentum id. Quisque laoreet felis quis dui tincidunt eu lobortis turpis congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Vivamus eget ipsum ut mauris dictum aliquam. Fusce commodo commodo arcu, vulputate euismod urna dapibus ut. Maecenas in nibh quam. Integer sagittis, sem sollicitudin mollis consectetur, dui lorem ultrices eros, id vehicula nunc erat at felis. Vivamus accumsan pulvinar arcu vitae lacinia. Praesent accumsan arcu ac arcu dictum vehicula. Vivamus venenatis dolor eget nisi feugiat sed sodales nibh iaculis. Nunc euismod libero vitae leo accumsan ut placerat dui dictum. Suspendisse volutpat imperdiet purus at mollis. Vestibulum imperdiet euismod libero sed dictum. Nulla eget risus tellus, a pellentesque mauris.

Mauris arcu erat, semper eu tristique in, commodo venenatis dui. Maecenas iaculis, mi in mattis suscipit, justo justo malesuada risus, nec tristique diam risus eu augue. In id sapien libero. Curabitur dictum auctor nisi, vel pretium sapien convallis non. Sed non nisi tortor, nec aliquet erat. Maecenas posuere commodo ligula et placerat. Maecenas ullamcorper, lacus sed sodales varius, sapien velit pulvinar metus, tempor dignissim urna neque eget nisi. Aliquam ut felis eu tellus hendrerit euismod vel vitae risus. Ut convallis lacinia tellus, sit amet dictum justo facilisis bibendum. Maecenas consectetur vestibulum lectus id ullamcorper. Quisque mollis lobortis imperdiet. Nunc sit amet augue et ipsum scelerisque adipiscing vitae a orci. Phasellus sed justo non ligula mattis hendrerit. Cras molestie egestas leo, et varius tellus congue ac. Mauris tincidunt lectus id nisl tincidunt vehicula. Aenean id nibh vel mauris blandit adipiscing.

Integer volutpat blandit posuere. Ut pellentesque nunc eget justo rutrum tincidunt. Proin accumsan, libero ut auctor rhoncus, orci elit varius augue, non mollis diam odio eu est. Phasellus in mi vitae ipsum bibendum luctus ac non lectus. Vivamus in laoreet nisi. Maecenas id arcu at odio sagittis aliquam. Nam vel sapien non felis aliquet mattis. Sed facilisis iaculis gravida. Nunc dignissim tristique enim quis varius. Donec quis diam libero, a ullamcorper erat. Sed nec nisl at sem molestie porttitor. Fusce elit felis, tincidunt ut auctor non, mollis in mauris. Nullam sagittis viverra enim, id faucibus tellus suscipit at. Ut sagittis feugiat ultrices. Fusce ultricies, sapien a pellentesque venenatis, augue risus sodales arcu, id rhoncus ligula justo nec enim. Praesent eu massa eu tellus dapibus egestas condimentum ut felis.

Sed tincidunt placerat auctor. Morbi tellus quam, auctor et fringilla nec, laoreet eu risus. Cras ut eros vel dui sagittis ornare. Praesent vitae nisl nibh, id condimentum libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras molestie, ligula id ornare vestibulum, nisi nibh vestibulum mauris, vitae mattis quam nunc ac leo. Vivamus pharetra enim sed diam blandit ac varius ipsum fermentum. Vivamus vulputate arcu sit amet eros vestibulum non vestibulum arcu faucibus. In lobortis enim mi, eu varius libero. Praesent orci est, auctor eget ultricies sed, lacinia ut tortor. Praesent quis nisl eros. Proin venenatis mollis mollis.
ipsum;
?>